name: Build Nintendo DS ROM

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:20260610

    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name:  Build .nds
        
        run: make
        env:
  DEVKITARM: /opt/devkitpro/devkitARM
      - name: 
        uses: 
        with:  
          name:  ginseng-strip-gta-nds
          path:  "*.nds"
          if-no-files-found:error
          
